"""Create users table

Revision ID: 35199a4f8915
Revises: 864cd23fcdf1
Create Date: 2025-07-09 13:48:54.873488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35199a4f8915"
down_revision: Union[str, Sequence[str], None] = "864cd23fcdf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, "users", ["email"])
    op.drop_column("users", "country_code")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "phone_number", sa.VARCHAR(length=11), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "country_code", sa.VARCHAR(length=2), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
