"""Alter embeddings vector dimension to 768

Revision ID: d58a55a16a46
Revises: 72da1063738d
Create Date: 2025-07-10 20:54:58.391711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd58a55a16a46'
down_revision: Union[str, Sequence[str], None] = '72da1063738d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'embeddings',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=758),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'embeddings',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=758),
               existing_nullable=True)
    # ### end Alembic commands ###
